# Generated by Django 5.1.15 on 2026-03-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('repo_path', models.CharField(help_text='Absolute path to the git repository', max_length=1024)),
                ('remote_url', models.URLField(blank=True, help_text='e.g. https://github.com/user/repo')),
                ('description', models.TextField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('llm_config', models.ForeignKey(blank=True, help_text='Override default LLM for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='providers.llmconfig')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
