# Generated by Django 5.1.15 on 2026-03-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='backlog', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('prompt', models.TextField()),
                ('task_type', models.CharField(choices=[('one_shot', 'One Shot'), ('evergreen', 'Evergreen'), ('chained', 'Chained')], default='one_shot', max_length=20)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='backlog', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('recurrence_rule', models.CharField(blank=True, help_text="Cron expression for evergreen tasks, e.g. '0 9 * * 1'", max_length=255)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('chain_order', models.PositiveIntegerField(default=0)),
                ('estimated_tokens', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('kanban_order', models.PositiveIntegerField(default=0)),
                ('tmux_session', models.CharField(blank=True, max_length=255)),
                ('result_summary', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='providers.llmconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskchain')),
            ],
            options={
                'ordering': ['kanban_order', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('output_log', models.TextField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('tmux_session', models.CharField(blank=True, max_length=255)),
                ('tmux_window', models.CharField(blank=True, max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
