# Generated by Django 5.1.15 on 2026-03-20 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="prompt",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
    ]
