# Generated by Django 5.1.15 on 2026-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ignore_idle',
            field=models.BooleanField(default=False, help_text='Run even when user is active (for scheduled evergreen tasks)'),
        ),
    ]
