# Generated by Django 5.1.15 on 2026-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_schedule_max_concurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dangerously_skip_permissions',
            field=models.BooleanField(default=False, help_text='Pass --dangerously-skip-permissions to Claude Code CLI (no tool confirmations)'),
        ),
    ]
