# Generated by Django 5.1.15 on 2026-03-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_dangerously_skip_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='loop_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times to re-run after completion (0 = no loop)'),
        ),
        migrations.AddField(
            model_name='task',
            name='loop_iterations_done',
            field=models.PositiveIntegerField(default=0, help_text='Iterations completed so far in the current loop'),
        ),
    ]
