# Generated by Django 5.1.15 on 2026-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('claude_max', 'Claude Max (CLI)'), ('anthropic', 'Anthropic API'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama (Local)')], max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('base_url', models.URLField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('claude_cli_path', models.CharField(default='claude', max_length=500)),
                ('max_tokens', models.PositiveIntegerField(default=8192)),
                ('temperature', models.FloatField(default=0.7)),
                ('system_prompt', models.TextField(blank=True)),
                ('extra_params', models.JSONField(default=dict)),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
