# Generated by Django 5.1.15 on 2026-03-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('idle_threshold_minutes', models.PositiveIntegerField(default=15, help_text="Minutes of inactivity before considered 'short idle'")),
                ('away_threshold_hours', models.PositiveIntegerField(default=1, help_text="Hours since last activity before considered 'away'")),
                ('max_run_window_hours', models.PositiveIntegerField(default=4, help_text='Max hours of continuous task running while idle')),
                ('allowed_hours', models.JSONField(blank=True, default=list, help_text='e.g. [{"start": 22, "end": 8}] — empty means always allowed')),
                ('allowed_days', models.IntegerField(default=127)),
                ('enable_token_spreading', models.BooleanField(default=True, help_text='Prevent burning all tokens at the start of the week')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IdleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idle_ms', models.BigIntegerField(help_text='Milliseconds idle from xprintidle')),
                ('is_idle', models.BooleanField()),
                ('source', models.CharField(help_text="'xprintidle' or 'time_based'", max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scheduling__created_0b65be_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_limit', models.PositiveIntegerField(default=1000000, help_text='Estimated weekly token limit (for Claude Max: configure based on your plan)')),
                ('reset_weekday', models.PositiveIntegerField(default=1, help_text='ISO weekday when budget resets (1=Monday)')),
                ('reset_time', models.TimeField(default='09:00')),
                ('budget_curve', models.JSONField(blank=True, default=list, help_text='Token spreading curve. Leave empty to disable.')),
                ('tokens_used_this_week', models.PositiveIntegerField(default=0)),
                ('tokens_used_this_session', models.PositiveIntegerField(default=0)),
                ('session_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='When the current Claude session expires — triggers drain mode', null=True)),
                ('drain_threshold_hours', models.PositiveIntegerField(default=24, help_text='Hours before session expiry to enter drain mode')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='providers.llmconfig')),
            ],
            options={
                'verbose_name': 'Token Budget',
            },
        ),
    ]
