# Generated by Django 5.1.15 on 2026-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_register_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='max_concurrent_tasks',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of tasks that can run simultaneously'),
        ),
    ]
